var annotated =
[
    [ "casmo", null, [
      [ "py", "classcasmo_1_1py.html", null ]
    ] ],
    [ "openmoc", null, [
      [ "compatible", null, [
        [ "casmo", "namespaceopenmoc_1_1compatible_1_1casmo.html", "namespaceopenmoc_1_1compatible_1_1casmo" ]
      ] ],
      [ "log", "namespaceopenmoc_1_1log.html", null ],
      [ "materialize", "namespaceopenmoc_1_1materialize.html", null ],
      [ "options", "namespaceopenmoc_1_1options.html", "namespaceopenmoc_1_1options" ],
      [ "process", "namespaceopenmoc_1_1process.html", null ]
    ] ],
    [ "Cell", "classCell.html", "classCell" ],
    [ "Circle", "classCircle.html", "classCircle" ],
    [ "Cmfd", "classCmfd.html", "classCmfd" ],
    [ "CPUSolver", "classCPUSolver.html", "classCPUSolver" ],
    [ "dev_material", "structdev__material.html", "structdev__material" ],
    [ "dev_segment", "structdev__segment.html", "structdev__segment" ],
    [ "dev_track", "structdev__track.html", "structdev__track" ],
    [ "EqualAnglePolarQuad", "classEqualAnglePolarQuad.html", "classEqualAnglePolarQuad" ],
    [ "EqualWeightPolarQuad", "classEqualWeightPolarQuad.html", "classEqualWeightPolarQuad" ],
    [ "ExpEvaluator", "classExpEvaluator.html", "classExpEvaluator" ],
    [ "FixedHashMap", "classFixedHashMap.html", "classFixedHashMap" ],
    [ "fsr_data", "structfsr__data.html", "structfsr__data" ],
    [ "Geometry", "classGeometry.html", "classGeometry" ],
    [ "GLPolarQuad", "classGLPolarQuad.html", "classGLPolarQuad" ],
    [ "GPUExpEvaluator", "classGPUExpEvaluator.html", "classGPUExpEvaluator" ],
    [ "GPUSolver", "classGPUSolver.html", "classGPUSolver" ],
    [ "isinf_test", "structisinf__test.html", "structisinf__test" ],
    [ "isnan_test", "structisnan__test.html", "structisnan__test" ],
    [ "Lattice", "classLattice.html", "classLattice" ],
    [ "LeonardPolarQuad", "classLeonardPolarQuad.html", "classLeonardPolarQuad" ],
    [ "LocalCoords", "classLocalCoords.html", "classLocalCoords" ],
    [ "Material", "classMaterial.html", "classMaterial" ],
    [ "ParallelHashMap", "classParallelHashMap.html", "classParallelHashMap" ],
    [ "Plane", "classPlane.html", "classPlane" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "PolarQuad", "classPolarQuad.html", "classPolarQuad" ],
    [ "second_t", "structsecond__t.html", "structsecond__t" ],
    [ "segment", "structsegment.html", "structsegment" ],
    [ "Solver", "classSolver.html", "classSolver" ],
    [ "Surface", "classSurface.html", "classSurface" ],
    [ "surface_halfspace", "structsurface__halfspace.html", "structsurface__halfspace" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Track", "classTrack.html", "classTrack" ],
    [ "TrackGenerator", "classTrackGenerator.html", "classTrackGenerator" ],
    [ "TYPolarQuad", "classTYPolarQuad.html", "classTYPolarQuad" ],
    [ "Universe", "classUniverse.html", "classUniverse" ],
    [ "VectorizedSolver", "classVectorizedSolver.html", "classVectorizedSolver" ],
    [ "XPlane", "classXPlane.html", "classXPlane" ],
    [ "YPlane", "classYPlane.html", "classYPlane" ],
    [ "ZPlane", "classZPlane.html", "classZPlane" ]
];