var annotated =
[
    [ "openmoc", null, [
      [ "log", "namespaceopenmoc_1_1log.html", null ],
      [ "materialize", "namespaceopenmoc_1_1materialize.html", null ],
      [ "openmoc", null, [
        [ "_object", "classopenmoc_1_1openmoc_1_1__object.html", null ],
        [ "Cell", "classopenmoc_1_1openmoc_1_1Cell.html", "classopenmoc_1_1openmoc_1_1Cell" ],
        [ "CellBasic", "classopenmoc_1_1openmoc_1_1CellBasic.html", "classopenmoc_1_1openmoc_1_1CellBasic" ],
        [ "CellFill", "classopenmoc_1_1openmoc_1_1CellFill.html", "classopenmoc_1_1openmoc_1_1CellFill" ],
        [ "Geometry", "classopenmoc_1_1openmoc_1_1Geometry.html", "classopenmoc_1_1openmoc_1_1Geometry" ],
        [ "LocalCoords", "classopenmoc_1_1openmoc_1_1LocalCoords.html", "classopenmoc_1_1openmoc_1_1LocalCoords" ],
        [ "Material", "classopenmoc_1_1openmoc_1_1Material.html", "classopenmoc_1_1openmoc_1_1Material" ],
        [ "Point", "classopenmoc_1_1openmoc_1_1Point.html", "classopenmoc_1_1openmoc_1_1Point" ],
        [ "Quadrature", "classopenmoc_1_1openmoc_1_1Quadrature.html", "classopenmoc_1_1openmoc_1_1Quadrature" ],
        [ "Solver", "classopenmoc_1_1openmoc_1_1Solver.html", "classopenmoc_1_1openmoc_1_1Solver" ],
        [ "CPUSolver", "classopenmoc_1_1openmoc_1_1CPUSolver.html", "classopenmoc_1_1openmoc_1_1CPUSolver" ],
        [ "ThreadPrivateSolver", "classopenmoc_1_1openmoc_1_1ThreadPrivateSolver.html", "classopenmoc_1_1openmoc_1_1ThreadPrivateSolver" ],
        [ "Surface", "classopenmoc_1_1openmoc_1_1Surface.html", "classopenmoc_1_1openmoc_1_1Surface" ],
        [ "Plane", "classopenmoc_1_1openmoc_1_1Plane.html", "classopenmoc_1_1openmoc_1_1Plane" ],
        [ "XPlane", "classopenmoc_1_1openmoc_1_1XPlane.html", "classopenmoc_1_1openmoc_1_1XPlane" ],
        [ "YPlane", "classopenmoc_1_1openmoc_1_1YPlane.html", "classopenmoc_1_1openmoc_1_1YPlane" ],
        [ "ZPlane", "classopenmoc_1_1openmoc_1_1ZPlane.html", "classopenmoc_1_1openmoc_1_1ZPlane" ],
        [ "Circle", "classopenmoc_1_1openmoc_1_1Circle.html", "classopenmoc_1_1openmoc_1_1Circle" ],
        [ "Timer", "classopenmoc_1_1openmoc_1_1Timer.html", "classopenmoc_1_1openmoc_1_1Timer" ],
        [ "segment", "classopenmoc_1_1openmoc_1_1segment.html", "classopenmoc_1_1openmoc_1_1segment" ],
        [ "Track", "classopenmoc_1_1openmoc_1_1Track.html", "classopenmoc_1_1openmoc_1_1Track" ],
        [ "TrackGenerator", "classopenmoc_1_1openmoc_1_1TrackGenerator.html", "classopenmoc_1_1openmoc_1_1TrackGenerator" ],
        [ "Universe", "classopenmoc_1_1openmoc_1_1Universe.html", "classopenmoc_1_1openmoc_1_1Universe" ],
        [ "Lattice", "classopenmoc_1_1openmoc_1_1Lattice.html", "classopenmoc_1_1openmoc_1_1Lattice" ],
        [ "Cmfd", "classopenmoc_1_1openmoc_1_1Cmfd.html", "classopenmoc_1_1openmoc_1_1Cmfd" ],
        [ "Mesh", "classopenmoc_1_1openmoc_1_1Mesh.html", "classopenmoc_1_1openmoc_1_1Mesh" ]
      ] ],
      [ "options", "namespaceopenmoc_1_1options.html", "namespaceopenmoc_1_1options" ],
      [ "plotter", "namespaceopenmoc_1_1plotter.html", null ],
      [ "process", "namespaceopenmoc_1_1process.html", null ]
    ] ],
    [ "Cell", "classCell.html", "classCell" ],
    [ "CellBasic", "classCellBasic.html", "classCellBasic" ],
    [ "CellFill", "classCellFill.html", "classCellFill" ],
    [ "Circle", "classCircle.html", "classCircle" ],
    [ "Cmfd", "classCmfd.html", "classCmfd" ],
    [ "CPUSolver", "classCPUSolver.html", "classCPUSolver" ],
    [ "dev_material", "structdev__material.html", "structdev__material" ],
    [ "dev_segment", "structdev__segment.html", "structdev__segment" ],
    [ "dev_track", "structdev__track.html", "structdev__track" ],
    [ "Geometry", "classGeometry.html", "classGeometry" ],
    [ "GPUSolver", "classGPUSolver.html", "classGPUSolver" ],
    [ "Lattice", "classLattice.html", "classLattice" ],
    [ "LocalCoords", "classLocalCoords.html", "classLocalCoords" ],
    [ "Material", "classMaterial.html", "classMaterial" ],
    [ "Mesh", "classMesh.html", "classMesh" ],
    [ "Plane", "classPlane.html", "classPlane" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "Quadrature", "classQuadrature.html", "classQuadrature" ],
    [ "segment", "structsegment.html", "structsegment" ],
    [ "Solver", "classSolver.html", "classSolver" ],
    [ "Surface", "classSurface.html", "classSurface" ],
    [ "ThreadPrivateSolver", "classThreadPrivateSolver.html", "classThreadPrivateSolver" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Track", "classTrack.html", "classTrack" ],
    [ "TrackGenerator", "classTrackGenerator.html", "classTrackGenerator" ],
    [ "Universe", "classUniverse.html", "classUniverse" ],
    [ "VectorizedPrivateSolver", "classVectorizedPrivateSolver.html", "classVectorizedPrivateSolver" ],
    [ "VectorizedSolver", "classVectorizedSolver.html", "classVectorizedSolver" ],
    [ "XPlane", "classXPlane.html", "classXPlane" ],
    [ "YPlane", "classYPlane.html", "classYPlane" ],
    [ "ZPlane", "classZPlane.html", "classZPlane" ]
];