# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_openmoc_gnu_double', [dirname(__file__)])
        except ImportError:
            import _openmoc_gnu_double
            return _openmoc_gnu_double
        if fp is not None:
            try:
                _mod = imp.load_module('_openmoc_gnu_double', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _openmoc_gnu_double = swig_import_helper()
    del swig_import_helper
else:
    import _openmoc_gnu_double
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def cell_id():
  return _openmoc_gnu_double.cell_id()
cell_id = _openmoc_gnu_double.cell_id
MATERIAL = _openmoc_gnu_double.MATERIAL
FILL = _openmoc_gnu_double.FILL
class Cell(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cell, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cell, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _openmoc_gnu_double.delete_Cell
    __del__ = lambda self : None;
    def getUid(self): return _openmoc_gnu_double.Cell_getUid(self)
    def getId(self): return _openmoc_gnu_double.Cell_getId(self)
    def getType(self): return _openmoc_gnu_double.Cell_getType(self)
    def getUniverse(self): return _openmoc_gnu_double.Cell_getUniverse(self)
    def getNumSurfaces(self): return _openmoc_gnu_double.Cell_getNumSurfaces(self)
    def getSurfaces(self): return _openmoc_gnu_double.Cell_getSurfaces(self)
    def getNumFSRs(self): return _openmoc_gnu_double.Cell_getNumFSRs(self)
    def setUniverse(self, *args, **kwargs): return _openmoc_gnu_double.Cell_setUniverse(self, *args, **kwargs)
    def addSurface(self, *args, **kwargs): return _openmoc_gnu_double.Cell_addSurface(self, *args, **kwargs)
    def setSurfacePointer(self, *args, **kwargs): return _openmoc_gnu_double.Cell_setSurfacePointer(self, *args, **kwargs)
    def cellContains(self, *args): return _openmoc_gnu_double.Cell_cellContains(self, *args)
    def minSurfaceDist(self, *args, **kwargs): return _openmoc_gnu_double.Cell_minSurfaceDist(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.Cell_toString(self)
    def printString(self): return _openmoc_gnu_double.Cell_printString(self)
Cell_swigregister = _openmoc_gnu_double.Cell_swigregister
Cell_swigregister(Cell)

class CellBasic(Cell):
    __swig_setmethods__ = {}
    for _s in [Cell]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CellBasic, name, value)
    __swig_getmethods__ = {}
    for _s in [Cell]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CellBasic, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_CellBasic(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def getMaterial(self): return _openmoc_gnu_double.CellBasic_getMaterial(self)
    def getNumRings(self): return _openmoc_gnu_double.CellBasic_getNumRings(self)
    def getNumSectors(self): return _openmoc_gnu_double.CellBasic_getNumSectors(self)
    def getNumFSRs(self): return _openmoc_gnu_double.CellBasic_getNumFSRs(self)
    def setNumRings(self, *args, **kwargs): return _openmoc_gnu_double.CellBasic_setNumRings(self, *args, **kwargs)
    def setNumSectors(self, *args, **kwargs): return _openmoc_gnu_double.CellBasic_setNumSectors(self, *args, **kwargs)
    def clone(self): return _openmoc_gnu_double.CellBasic_clone(self)
    def subdivideCell(self): return _openmoc_gnu_double.CellBasic_subdivideCell(self)
    def toString(self): return _openmoc_gnu_double.CellBasic_toString(self)
    def printString(self): return _openmoc_gnu_double.CellBasic_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_CellBasic
    __del__ = lambda self : None;
CellBasic_swigregister = _openmoc_gnu_double.CellBasic_swigregister
CellBasic_swigregister(CellBasic)

class CellFill(Cell):
    __swig_setmethods__ = {}
    for _s in [Cell]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CellFill, name, value)
    __swig_getmethods__ = {}
    for _s in [Cell]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CellFill, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_CellFill(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def getUniverseFillId(self): return _openmoc_gnu_double.CellFill_getUniverseFillId(self)
    def getUniverseFill(self): return _openmoc_gnu_double.CellFill_getUniverseFill(self)
    def getNumFSRs(self): return _openmoc_gnu_double.CellFill_getNumFSRs(self)
    def setUniverseFill(self, *args, **kwargs): return _openmoc_gnu_double.CellFill_setUniverseFill(self, *args, **kwargs)
    def setUniverseFillPointer(self, *args, **kwargs): return _openmoc_gnu_double.CellFill_setUniverseFillPointer(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.CellFill_toString(self)
    def printString(self): return _openmoc_gnu_double.CellFill_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_CellFill
    __del__ = lambda self : None;
CellFill_swigregister = _openmoc_gnu_double.CellFill_swigregister
CellFill_swigregister(CellFill)

class FlatSourceRegion(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FlatSourceRegion, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FlatSourceRegion, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _openmoc_gnu_double.new_FlatSourceRegion()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_FlatSourceRegion
    __del__ = lambda self : None;
    def getUid(self): return _openmoc_gnu_double.FlatSourceRegion_getUid(self)
    def getMaterial(self): return _openmoc_gnu_double.FlatSourceRegion_getMaterial(self)
    def getVolume(self): return _openmoc_gnu_double.FlatSourceRegion_getVolume(self)
    def setMaterial(self, *args, **kwargs): return _openmoc_gnu_double.FlatSourceRegion_setMaterial(self, *args, **kwargs)
    def setVolume(self, *args, **kwargs): return _openmoc_gnu_double.FlatSourceRegion_setVolume(self, *args, **kwargs)
    def incrementVolume(self, *args, **kwargs): return _openmoc_gnu_double.FlatSourceRegion_incrementVolume(self, *args, **kwargs)
FlatSourceRegion_swigregister = _openmoc_gnu_double.FlatSourceRegion_swigregister
FlatSourceRegion_swigregister(FlatSourceRegion)

class Geometry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Geometry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Geometry, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _openmoc_gnu_double.new_Geometry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Geometry
    __del__ = lambda self : None;
    def getWidth(self): return _openmoc_gnu_double.Geometry_getWidth(self)
    def getHeight(self): return _openmoc_gnu_double.Geometry_getHeight(self)
    def getXMin(self): return _openmoc_gnu_double.Geometry_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.Geometry_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.Geometry_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.Geometry_getYMax(self)
    def getBCTop(self): return _openmoc_gnu_double.Geometry_getBCTop(self)
    def getBCBottom(self): return _openmoc_gnu_double.Geometry_getBCBottom(self)
    def getBCLeft(self): return _openmoc_gnu_double.Geometry_getBCLeft(self)
    def getBCRight(self): return _openmoc_gnu_double.Geometry_getBCRight(self)
    def getNumFSRs(self): return _openmoc_gnu_double.Geometry_getNumFSRs(self)
    def getNumEnergyGroups(self): return _openmoc_gnu_double.Geometry_getNumEnergyGroups(self)
    def getNumMaterials(self): return _openmoc_gnu_double.Geometry_getNumMaterials(self)
    def getFSRtoCellMap(self): return _openmoc_gnu_double.Geometry_getFSRtoCellMap(self)
    def getFSRtoMaterialMap(self): return _openmoc_gnu_double.Geometry_getFSRtoMaterialMap(self)
    def getMaxSegmentLength(self): return _openmoc_gnu_double.Geometry_getMaxSegmentLength(self)
    def getMinSegmentLength(self): return _openmoc_gnu_double.Geometry_getMinSegmentLength(self)
    def getMaterials(self): return _openmoc_gnu_double.Geometry_getMaterials(self)
    def getMaterial(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_getMaterial(self, *args, **kwargs)
    def getSurface(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_getSurface(self, *args, **kwargs)
    def getCell(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_getCell(self, *args, **kwargs)
    def getUniverse(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_getUniverse(self, *args, **kwargs)
    def getLattice(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_getLattice(self, *args, **kwargs)
    def addMaterial(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_addMaterial(self, *args, **kwargs)
    def addSurface(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_addSurface(self, *args, **kwargs)
    def addCell(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_addCell(self, *args, **kwargs)
    def addUniverse(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_addUniverse(self, *args, **kwargs)
    def addLattice(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_addLattice(self, *args, **kwargs)
    def findCell(self, *args): return _openmoc_gnu_double.Geometry_findCell(self, *args)
    def findFSRId(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_findFSRId(self, *args, **kwargs)
    def subdivideCells(self): return _openmoc_gnu_double.Geometry_subdivideCells(self)
    def initializeFlatSourceRegions(self): return _openmoc_gnu_double.Geometry_initializeFlatSourceRegions(self)
    def segmentize(self, *args, **kwargs): return _openmoc_gnu_double.Geometry_segmentize(self, *args, **kwargs)
    def computePinPowers(self, *args): return _openmoc_gnu_double.Geometry_computePinPowers(self, *args)
    def toString(self): return _openmoc_gnu_double.Geometry_toString(self)
    def printString(self): return _openmoc_gnu_double.Geometry_printString(self)
Geometry_swigregister = _openmoc_gnu_double.Geometry_swigregister
Geometry_swigregister(Geometry)

UNIV = _openmoc_gnu_double.UNIV
LAT = _openmoc_gnu_double.LAT
class LocalCoords(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LocalCoords, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LocalCoords, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_LocalCoords(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_LocalCoords
    __del__ = lambda self : None;
    def getType(self): return _openmoc_gnu_double.LocalCoords_getType(self)
    def getUniverse(self): return _openmoc_gnu_double.LocalCoords_getUniverse(self)
    def getCell(self): return _openmoc_gnu_double.LocalCoords_getCell(self)
    def getLattice(self): return _openmoc_gnu_double.LocalCoords_getLattice(self)
    def getLatticeX(self): return _openmoc_gnu_double.LocalCoords_getLatticeX(self)
    def getLatticeY(self): return _openmoc_gnu_double.LocalCoords_getLatticeY(self)
    def getX(self): return _openmoc_gnu_double.LocalCoords_getX(self)
    def getY(self): return _openmoc_gnu_double.LocalCoords_getY(self)
    def getPoint(self): return _openmoc_gnu_double.LocalCoords_getPoint(self)
    def getNext(self): return _openmoc_gnu_double.LocalCoords_getNext(self)
    def getPrev(self): return _openmoc_gnu_double.LocalCoords_getPrev(self)
    def setType(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setType(self, *args, **kwargs)
    def setUniverse(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setUniverse(self, *args, **kwargs)
    def setCell(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setCell(self, *args, **kwargs)
    def setLattice(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setLattice(self, *args, **kwargs)
    def setLatticeX(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setLatticeX(self, *args, **kwargs)
    def setLatticeY(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setLatticeY(self, *args, **kwargs)
    def setX(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setX(self, *args, **kwargs)
    def setY(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setY(self, *args, **kwargs)
    def setNext(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setNext(self, *args, **kwargs)
    def setPrev(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_setPrev(self, *args, **kwargs)
    def getLowestLevel(self): return _openmoc_gnu_double.LocalCoords_getLowestLevel(self)
    def adjustCoords(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_adjustCoords(self, *args, **kwargs)
    def updateMostLocal(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_updateMostLocal(self, *args, **kwargs)
    def prune(self): return _openmoc_gnu_double.LocalCoords_prune(self)
    def copyCoords(self, *args, **kwargs): return _openmoc_gnu_double.LocalCoords_copyCoords(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.LocalCoords_toString(self)
LocalCoords_swigregister = _openmoc_gnu_double.LocalCoords_swigregister
LocalCoords_swigregister(LocalCoords)

DEBUG = _openmoc_gnu_double.DEBUG
INFO = _openmoc_gnu_double.INFO
NORMAL = _openmoc_gnu_double.NORMAL
SEPARATOR = _openmoc_gnu_double.SEPARATOR
HEADER = _openmoc_gnu_double.HEADER
TITLE = _openmoc_gnu_double.TITLE
WARNING = _openmoc_gnu_double.WARNING
CRITICAL = _openmoc_gnu_double.CRITICAL
RESULT = _openmoc_gnu_double.RESULT
UNITTEST = _openmoc_gnu_double.UNITTEST
ERROR = _openmoc_gnu_double.ERROR

def set_err(*args, **kwargs):
  return _openmoc_gnu_double.set_err(*args, **kwargs)
set_err = _openmoc_gnu_double.set_err

def setOutputDirectory(*args, **kwargs):
  return _openmoc_gnu_double.setOutputDirectory(*args, **kwargs)
setOutputDirectory = _openmoc_gnu_double.setOutputDirectory

def getOutputDirectory():
  return _openmoc_gnu_double.getOutputDirectory()
getOutputDirectory = _openmoc_gnu_double.getOutputDirectory

def setLogfileName(*args, **kwargs):
  return _openmoc_gnu_double.setLogfileName(*args, **kwargs)
setLogfileName = _openmoc_gnu_double.setLogfileName

def getLogfileName():
  return _openmoc_gnu_double.getLogfileName()
getLogfileName = _openmoc_gnu_double.getLogfileName

def setSeparatorCharacter(*args, **kwargs):
  return _openmoc_gnu_double.setSeparatorCharacter(*args, **kwargs)
setSeparatorCharacter = _openmoc_gnu_double.setSeparatorCharacter

def getSeparatorCharacter():
  return _openmoc_gnu_double.getSeparatorCharacter()
getSeparatorCharacter = _openmoc_gnu_double.getSeparatorCharacter

def setHeaderCharacter(*args, **kwargs):
  return _openmoc_gnu_double.setHeaderCharacter(*args, **kwargs)
setHeaderCharacter = _openmoc_gnu_double.setHeaderCharacter

def getHeaderCharacter():
  return _openmoc_gnu_double.getHeaderCharacter()
getHeaderCharacter = _openmoc_gnu_double.getHeaderCharacter

def setTitleCharacter(*args, **kwargs):
  return _openmoc_gnu_double.setTitleCharacter(*args, **kwargs)
setTitleCharacter = _openmoc_gnu_double.setTitleCharacter

def getTitleCharacter():
  return _openmoc_gnu_double.getTitleCharacter()
getTitleCharacter = _openmoc_gnu_double.getTitleCharacter

def setLineLength(*args, **kwargs):
  return _openmoc_gnu_double.setLineLength(*args, **kwargs)
setLineLength = _openmoc_gnu_double.setLineLength

def log_setlevel(*args):
  return _openmoc_gnu_double.log_setlevel(*args)
log_setlevel = _openmoc_gnu_double.log_setlevel

def get_loglevel():
  return _openmoc_gnu_double.get_loglevel()
get_loglevel = _openmoc_gnu_double.get_loglevel

def log_printf(*args, **kwargs):
  return _openmoc_gnu_double.log_printf(*args, **kwargs)
log_printf = _openmoc_gnu_double.log_printf

def createMultilineMsg(*args, **kwargs):
  return _openmoc_gnu_double.createMultilineMsg(*args, **kwargs)
createMultilineMsg = _openmoc_gnu_double.createMultilineMsg
SIGMA_T_THRESH = _openmoc_gnu_double.SIGMA_T_THRESH

def material_id():
  return _openmoc_gnu_double.material_id()
material_id = _openmoc_gnu_double.material_id
class Material(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Material, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Material, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Material(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Material
    __del__ = lambda self : None;
    def getUid(self): return _openmoc_gnu_double.Material_getUid(self)
    def getId(self): return _openmoc_gnu_double.Material_getId(self)
    def getNumEnergyGroups(self): return _openmoc_gnu_double.Material_getNumEnergyGroups(self)
    def getSigmaT(self): return _openmoc_gnu_double.Material_getSigmaT(self)
    def getSigmaA(self): return _openmoc_gnu_double.Material_getSigmaA(self)
    def getSigmaS(self): return _openmoc_gnu_double.Material_getSigmaS(self)
    def getSigmaF(self): return _openmoc_gnu_double.Material_getSigmaF(self)
    def getNuSigmaF(self): return _openmoc_gnu_double.Material_getNuSigmaF(self)
    def getChi(self): return _openmoc_gnu_double.Material_getChi(self)
    def setNumEnergyGroups(self, *args, **kwargs): return _openmoc_gnu_double.Material_setNumEnergyGroups(self, *args, **kwargs)
    def setSigmaT(self, *args): return _openmoc_gnu_double.Material_setSigmaT(self, *args)
    def setSigmaA(self, *args): return _openmoc_gnu_double.Material_setSigmaA(self, *args)
    def setSigmaS(self, *args): return _openmoc_gnu_double.Material_setSigmaS(self, *args)
    def setSigmaF(self, *args): return _openmoc_gnu_double.Material_setSigmaF(self, *args)
    def setNuSigmaF(self, *args): return _openmoc_gnu_double.Material_setNuSigmaF(self, *args)
    def setChi(self, *args): return _openmoc_gnu_double.Material_setChi(self, *args)
    def checkSigmaT(self): return _openmoc_gnu_double.Material_checkSigmaT(self)
    def toString(self): return _openmoc_gnu_double.Material_toString(self)
    def printString(self): return _openmoc_gnu_double.Material_printString(self)
Material_swigregister = _openmoc_gnu_double.Material_swigregister
Material_swigregister(Material)

class Point(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Point, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Point, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _openmoc_gnu_double.new_Point()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Point
    __del__ = lambda self : None;
    def setCoords(self, *args, **kwargs): return _openmoc_gnu_double.Point_setCoords(self, *args, **kwargs)
    def getX(self): return _openmoc_gnu_double.Point_getX(self)
    def getY(self): return _openmoc_gnu_double.Point_getY(self)
    def setX(self, *args, **kwargs): return _openmoc_gnu_double.Point_setX(self, *args, **kwargs)
    def setY(self, *args, **kwargs): return _openmoc_gnu_double.Point_setY(self, *args, **kwargs)
    def distance(self, *args): return _openmoc_gnu_double.Point_distance(self, *args)
    def toString(self): return _openmoc_gnu_double.Point_toString(self)
Point_swigregister = _openmoc_gnu_double.Point_swigregister
Point_swigregister(Point)

LEONARD = _openmoc_gnu_double.LEONARD
TABUCHI = _openmoc_gnu_double.TABUCHI
class Quadrature(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Quadrature, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Quadrature, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Quadrature(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Quadrature
    __del__ = lambda self : None;
    def getNumPolarAngles(self): return _openmoc_gnu_double.Quadrature_getNumPolarAngles(self)
    def getType(self): return _openmoc_gnu_double.Quadrature_getType(self)
    def getSinTheta(self, *args, **kwargs): return _openmoc_gnu_double.Quadrature_getSinTheta(self, *args, **kwargs)
    def getWeight(self, *args, **kwargs): return _openmoc_gnu_double.Quadrature_getWeight(self, *args, **kwargs)
    def getMultiple(self, *args, **kwargs): return _openmoc_gnu_double.Quadrature_getMultiple(self, *args, **kwargs)
    def getSinThetas(self): return _openmoc_gnu_double.Quadrature_getSinThetas(self)
    def getWeights(self): return _openmoc_gnu_double.Quadrature_getWeights(self)
    def getMultiples(self): return _openmoc_gnu_double.Quadrature_getMultiples(self)
    def toString(self): return _openmoc_gnu_double.Quadrature_toString(self)
Quadrature_swigregister = _openmoc_gnu_double.Quadrature_swigregister
Quadrature_swigregister(Quadrature)

FOUR_PI = _openmoc_gnu_double.FOUR_PI
ONE_OVER_FOUR_PI = _openmoc_gnu_double.ONE_OVER_FOUR_PI
class Solver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solver, name)
    __repr__ = _swig_repr
    def __init__(self, geom=None, track_generator=None, num_threads=1): 
        this = _openmoc_gnu_double.new_Solver(geom, track_generator, num_threads)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Solver
    __del__ = lambda self : None;
    def getGeometry(self): return _openmoc_gnu_double.Solver_getGeometry(self)
    def getTrackGenerator(self): return _openmoc_gnu_double.Solver_getTrackGenerator(self)
    def getNumThreads(self): return _openmoc_gnu_double.Solver_getNumThreads(self)
    def getNumPolarAngles(self): return _openmoc_gnu_double.Solver_getNumPolarAngles(self)
    def getPolarQuadratureType(self): return _openmoc_gnu_double.Solver_getPolarQuadratureType(self)
    def getNumIterations(self): return _openmoc_gnu_double.Solver_getNumIterations(self)
    def getSourceConvergenceThreshold(self): return _openmoc_gnu_double.Solver_getSourceConvergenceThreshold(self)
    def getFluxConvergenceThreshold(self): return _openmoc_gnu_double.Solver_getFluxConvergenceThreshold(self)
    def getFSRScalarFlux(self, *args, **kwargs): return _openmoc_gnu_double.Solver_getFSRScalarFlux(self, *args, **kwargs)
    def getFSRScalarFluxes(self): return _openmoc_gnu_double.Solver_getFSRScalarFluxes(self)
    def getFSRPowers(self): return _openmoc_gnu_double.Solver_getFSRPowers(self)
    def getFSRPinPowers(self): return _openmoc_gnu_double.Solver_getFSRPinPowers(self)
    def setNumThreads(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setNumThreads(self, *args, **kwargs)
    def setGeometry(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setGeometry(self, *args, **kwargs)
    def setTrackGenerator(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setTrackGenerator(self, *args, **kwargs)
    def setPolarQuadratureType(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setPolarQuadratureType(self, *args, **kwargs)
    def setNumPolarAngles(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setNumPolarAngles(self, *args, **kwargs)
    def setSourceConvergenceThreshold(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setSourceConvergenceThreshold(self, *args, **kwargs)
    def setFluxConvergenceThreshold(self, *args, **kwargs): return _openmoc_gnu_double.Solver_setFluxConvergenceThreshold(self, *args, **kwargs)
    def convergeSource(self, *args, **kwargs): return _openmoc_gnu_double.Solver_convergeSource(self, *args, **kwargs)
    def computePinPowers(self): return _openmoc_gnu_double.Solver_computePinPowers(self)
Solver_swigregister = _openmoc_gnu_double.Solver_swigregister
Solver_swigregister(Solver)

ON_SURFACE_THRESH = _openmoc_gnu_double.ON_SURFACE_THRESH

def surf_id():
  return _openmoc_gnu_double.surf_id()
surf_id = _openmoc_gnu_double.surf_id
PLANE = _openmoc_gnu_double.PLANE
CIRCLE = _openmoc_gnu_double.CIRCLE
XPLANE = _openmoc_gnu_double.XPLANE
YPLANE = _openmoc_gnu_double.YPLANE
ZPLANE = _openmoc_gnu_double.ZPLANE
QUADRATIC = _openmoc_gnu_double.QUADRATIC
BOUNDARY_NONE = _openmoc_gnu_double.BOUNDARY_NONE
REFLECTIVE = _openmoc_gnu_double.REFLECTIVE
VACUUM = _openmoc_gnu_double.VACUUM
class Surface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Surface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Surface, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _openmoc_gnu_double.delete_Surface
    __del__ = lambda self : None;
    def getUid(self): return _openmoc_gnu_double.Surface_getUid(self)
    def getId(self): return _openmoc_gnu_double.Surface_getId(self)
    def getSurfaceType(self): return _openmoc_gnu_double.Surface_getSurfaceType(self)
    def getBoundaryType(self): return _openmoc_gnu_double.Surface_getBoundaryType(self)
    def getXMin(self): return _openmoc_gnu_double.Surface_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.Surface_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.Surface_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.Surface_getYMax(self)
    def setBoundaryType(self, *args, **kwargs): return _openmoc_gnu_double.Surface_setBoundaryType(self, *args, **kwargs)
    def evaluate(self, *args, **kwargs): return _openmoc_gnu_double.Surface_evaluate(self, *args, **kwargs)
    def intersection(self, *args, **kwargs): return _openmoc_gnu_double.Surface_intersection(self, *args, **kwargs)
    def onSurface(self, *args): return _openmoc_gnu_double.Surface_onSurface(self, *args)
    def getMinDistance(self, *args, **kwargs): return _openmoc_gnu_double.Surface_getMinDistance(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.Surface_toString(self)
    def printString(self): return _openmoc_gnu_double.Surface_printString(self)
Surface_swigregister = _openmoc_gnu_double.Surface_swigregister
Surface_swigregister(Surface)

class Plane(Surface):
    __swig_setmethods__ = {}
    for _s in [Surface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Plane, name, value)
    __swig_getmethods__ = {}
    for _s in [Surface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Plane, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Plane(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def getXMin(self): return _openmoc_gnu_double.Plane_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.Plane_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.Plane_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.Plane_getYMax(self)
    def evaluate(self, *args, **kwargs): return _openmoc_gnu_double.Plane_evaluate(self, *args, **kwargs)
    def intersection(self, *args, **kwargs): return _openmoc_gnu_double.Plane_intersection(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.Plane_toString(self)
    def printString(self): return _openmoc_gnu_double.Plane_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_Plane
    __del__ = lambda self : None;
Plane_swigregister = _openmoc_gnu_double.Plane_swigregister
Plane_swigregister(Plane)

class XPlane(Plane):
    __swig_setmethods__ = {}
    for _s in [Plane]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, XPlane, name, value)
    __swig_getmethods__ = {}
    for _s in [Plane]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, XPlane, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_XPlane(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def setX(self, *args, **kwargs): return _openmoc_gnu_double.XPlane_setX(self, *args, **kwargs)
    def getX(self): return _openmoc_gnu_double.XPlane_getX(self)
    def getXMin(self): return _openmoc_gnu_double.XPlane_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.XPlane_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.XPlane_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.XPlane_getYMax(self)
    def toString(self): return _openmoc_gnu_double.XPlane_toString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_XPlane
    __del__ = lambda self : None;
XPlane_swigregister = _openmoc_gnu_double.XPlane_swigregister
XPlane_swigregister(XPlane)

class YPlane(Plane):
    __swig_setmethods__ = {}
    for _s in [Plane]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, YPlane, name, value)
    __swig_getmethods__ = {}
    for _s in [Plane]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, YPlane, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_YPlane(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def setY(self, *args, **kwargs): return _openmoc_gnu_double.YPlane_setY(self, *args, **kwargs)
    def getY(self): return _openmoc_gnu_double.YPlane_getY(self)
    def getXMin(self): return _openmoc_gnu_double.YPlane_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.YPlane_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.YPlane_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.YPlane_getYMax(self)
    def toString(self): return _openmoc_gnu_double.YPlane_toString(self)
    def printString(self): return _openmoc_gnu_double.YPlane_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_YPlane
    __del__ = lambda self : None;
YPlane_swigregister = _openmoc_gnu_double.YPlane_swigregister
YPlane_swigregister(YPlane)

class ZPlane(Plane):
    __swig_setmethods__ = {}
    for _s in [Plane]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ZPlane, name, value)
    __swig_getmethods__ = {}
    for _s in [Plane]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ZPlane, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_ZPlane(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def setZ(self, *args, **kwargs): return _openmoc_gnu_double.ZPlane_setZ(self, *args, **kwargs)
    def getZ(self): return _openmoc_gnu_double.ZPlane_getZ(self)
    def getXMin(self): return _openmoc_gnu_double.ZPlane_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.ZPlane_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.ZPlane_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.ZPlane_getYMax(self)
    def toString(self): return _openmoc_gnu_double.ZPlane_toString(self)
    def printString(self): return _openmoc_gnu_double.ZPlane_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_ZPlane
    __del__ = lambda self : None;
ZPlane_swigregister = _openmoc_gnu_double.ZPlane_swigregister
ZPlane_swigregister(ZPlane)

class Circle(Surface):
    __swig_setmethods__ = {}
    for _s in [Surface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Circle, name, value)
    __swig_getmethods__ = {}
    for _s in [Surface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Circle, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Circle(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def getX0(self): return _openmoc_gnu_double.Circle_getX0(self)
    def getY0(self): return _openmoc_gnu_double.Circle_getY0(self)
    def getRadius(self): return _openmoc_gnu_double.Circle_getRadius(self)
    def getXMin(self): return _openmoc_gnu_double.Circle_getXMin(self)
    def getXMax(self): return _openmoc_gnu_double.Circle_getXMax(self)
    def getYMin(self): return _openmoc_gnu_double.Circle_getYMin(self)
    def getYMax(self): return _openmoc_gnu_double.Circle_getYMax(self)
    def evaluate(self, *args, **kwargs): return _openmoc_gnu_double.Circle_evaluate(self, *args, **kwargs)
    def intersection(self, *args, **kwargs): return _openmoc_gnu_double.Circle_intersection(self, *args, **kwargs)
    def toString(self): return _openmoc_gnu_double.Circle_toString(self)
    def printString(self): return _openmoc_gnu_double.Circle_printString(self)
    __swig_destroy__ = _openmoc_gnu_double.delete_Circle
    __del__ = lambda self : None;
Circle_swigregister = _openmoc_gnu_double.Circle_swigregister
Circle_swigregister(Circle)

class Timer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Timer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Timer, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _openmoc_gnu_double.new_Timer()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Timer
    __del__ = lambda self : None;
    __swig_getmethods__["Get"] = lambda x: _openmoc_gnu_double.Timer_Get
    if _newclass:Get = staticmethod(_openmoc_gnu_double.Timer_Get)
    def startTimer(self): return _openmoc_gnu_double.Timer_startTimer(self)
    def stopTimer(self): return _openmoc_gnu_double.Timer_stopTimer(self)
    def resetTimer(self): return _openmoc_gnu_double.Timer_resetTimer(self)
    def restartTimer(self): return _openmoc_gnu_double.Timer_restartTimer(self)
    def recordSplit(self, *args): return _openmoc_gnu_double.Timer_recordSplit(self, *args)
    def getTime(self): return _openmoc_gnu_double.Timer_getTime(self)
    def getSplit(self, *args): return _openmoc_gnu_double.Timer_getSplit(self, *args)
    def printSplits(self): return _openmoc_gnu_double.Timer_printSplits(self)
    def clearSplits(self): return _openmoc_gnu_double.Timer_clearSplits(self)
Timer_swigregister = _openmoc_gnu_double.Timer_swigregister
Timer_swigregister(Timer)

def Timer_Get():
  return _openmoc_gnu_double.Timer_Get()
Timer_Get = _openmoc_gnu_double.Timer_Get

class segment(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, segment, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, segment, name)
    __repr__ = _swig_repr
    __swig_setmethods__["_length"] = _openmoc_gnu_double.segment__length_set
    __swig_getmethods__["_length"] = _openmoc_gnu_double.segment__length_get
    if _newclass:_length = _swig_property(_openmoc_gnu_double.segment__length_get, _openmoc_gnu_double.segment__length_set)
    __swig_setmethods__["_material"] = _openmoc_gnu_double.segment__material_set
    __swig_getmethods__["_material"] = _openmoc_gnu_double.segment__material_get
    if _newclass:_material = _swig_property(_openmoc_gnu_double.segment__material_get, _openmoc_gnu_double.segment__material_set)
    __swig_setmethods__["_region_id"] = _openmoc_gnu_double.segment__region_id_set
    __swig_getmethods__["_region_id"] = _openmoc_gnu_double.segment__region_id_get
    if _newclass:_region_id = _swig_property(_openmoc_gnu_double.segment__region_id_get, _openmoc_gnu_double.segment__region_id_set)
    def __init__(self): 
        this = _openmoc_gnu_double.new_segment()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_segment
    __del__ = lambda self : None;
segment_swigregister = _openmoc_gnu_double.segment_swigregister
segment_swigregister(segment)

class Track(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Track, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Track, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _openmoc_gnu_double.new_Track()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Track
    __del__ = lambda self : None;
    def setValues(self, *args, **kwargs): return _openmoc_gnu_double.Track_setValues(self, *args, **kwargs)
    def setUid(self, *args, **kwargs): return _openmoc_gnu_double.Track_setUid(self, *args, **kwargs)
    def setPhi(self, *args, **kwargs): return _openmoc_gnu_double.Track_setPhi(self, *args, **kwargs)
    def setAzimAngleIndex(self, *args, **kwargs): return _openmoc_gnu_double.Track_setAzimAngleIndex(self, *args, **kwargs)
    def setReflIn(self, *args, **kwargs): return _openmoc_gnu_double.Track_setReflIn(self, *args, **kwargs)
    def setReflOut(self, *args, **kwargs): return _openmoc_gnu_double.Track_setReflOut(self, *args, **kwargs)
    def setBCIn(self, *args, **kwargs): return _openmoc_gnu_double.Track_setBCIn(self, *args, **kwargs)
    def setBCOut(self, *args, **kwargs): return _openmoc_gnu_double.Track_setBCOut(self, *args, **kwargs)
    def setTrackIn(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackIn(self, *args, **kwargs)
    def setTrackOut(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackOut(self, *args, **kwargs)
    def setTrackInI(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackInI(self, *args, **kwargs)
    def setTrackInJ(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackInJ(self, *args, **kwargs)
    def setTrackOutI(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackOutI(self, *args, **kwargs)
    def setTrackOutJ(self, *args, **kwargs): return _openmoc_gnu_double.Track_setTrackOutJ(self, *args, **kwargs)
    def getUid(self): return _openmoc_gnu_double.Track_getUid(self)
    def getEnd(self): return _openmoc_gnu_double.Track_getEnd(self)
    def getStart(self): return _openmoc_gnu_double.Track_getStart(self)
    def getPhi(self): return _openmoc_gnu_double.Track_getPhi(self)
    def getAzimAngleIndex(self): return _openmoc_gnu_double.Track_getAzimAngleIndex(self)
    def getSegment(self, *args, **kwargs): return _openmoc_gnu_double.Track_getSegment(self, *args, **kwargs)
    def getSegments(self): return _openmoc_gnu_double.Track_getSegments(self)
    def getNumSegments(self): return _openmoc_gnu_double.Track_getNumSegments(self)
    def getTrackIn(self): return _openmoc_gnu_double.Track_getTrackIn(self)
    def getTrackOut(self): return _openmoc_gnu_double.Track_getTrackOut(self)
    def getTrackInI(self): return _openmoc_gnu_double.Track_getTrackInI(self)
    def getTrackInJ(self): return _openmoc_gnu_double.Track_getTrackInJ(self)
    def getTrackOutI(self): return _openmoc_gnu_double.Track_getTrackOutI(self)
    def getTrackOutJ(self): return _openmoc_gnu_double.Track_getTrackOutJ(self)
    def isReflIn(self): return _openmoc_gnu_double.Track_isReflIn(self)
    def isReflOut(self): return _openmoc_gnu_double.Track_isReflOut(self)
    def getBCIn(self): return _openmoc_gnu_double.Track_getBCIn(self)
    def getBCOut(self): return _openmoc_gnu_double.Track_getBCOut(self)
    def contains(self, *args, **kwargs): return _openmoc_gnu_double.Track_contains(self, *args, **kwargs)
    def addSegment(self, *args, **kwargs): return _openmoc_gnu_double.Track_addSegment(self, *args, **kwargs)
    def clearSegments(self): return _openmoc_gnu_double.Track_clearSegments(self)
    def toString(self): return _openmoc_gnu_double.Track_toString(self)
Track_swigregister = _openmoc_gnu_double.Track_swigregister
Track_swigregister(Track)

class TrackGenerator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrackGenerator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TrackGenerator, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _openmoc_gnu_double.new_TrackGenerator(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_TrackGenerator
    __del__ = lambda self : None;
    def getNumAzim(self): return _openmoc_gnu_double.TrackGenerator_getNumAzim(self)
    def getTrackSpacing(self): return _openmoc_gnu_double.TrackGenerator_getTrackSpacing(self)
    def getGeometry(self): return _openmoc_gnu_double.TrackGenerator_getGeometry(self)
    def getNumTracks(self): return _openmoc_gnu_double.TrackGenerator_getNumTracks(self)
    def getNumTracksArray(self): return _openmoc_gnu_double.TrackGenerator_getNumTracksArray(self)
    def getNumSegments(self): return _openmoc_gnu_double.TrackGenerator_getNumSegments(self)
    def getNumSegmentsArray(self): return _openmoc_gnu_double.TrackGenerator_getNumSegmentsArray(self)
    def getTracks(self): return _openmoc_gnu_double.TrackGenerator_getTracks(self)
    def getAzimWeights(self): return _openmoc_gnu_double.TrackGenerator_getAzimWeights(self)
    def containsTracks(self): return _openmoc_gnu_double.TrackGenerator_containsTracks(self)
    def retrieveTrackCoords(self, *args, **kwargs): return _openmoc_gnu_double.TrackGenerator_retrieveTrackCoords(self, *args, **kwargs)
    def retrieveSegmentCoords(self, *args, **kwargs): return _openmoc_gnu_double.TrackGenerator_retrieveSegmentCoords(self, *args, **kwargs)
    def setNumAzim(self, *args, **kwargs): return _openmoc_gnu_double.TrackGenerator_setNumAzim(self, *args, **kwargs)
    def setTrackSpacing(self, *args, **kwargs): return _openmoc_gnu_double.TrackGenerator_setTrackSpacing(self, *args, **kwargs)
    def setGeometry(self, *args, **kwargs): return _openmoc_gnu_double.TrackGenerator_setGeometry(self, *args, **kwargs)
    def generateTracks(self): return _openmoc_gnu_double.TrackGenerator_generateTracks(self)
TrackGenerator_swigregister = _openmoc_gnu_double.TrackGenerator_swigregister
TrackGenerator_swigregister(TrackGenerator)

ON_LATTICE_CELL_THRESH = _openmoc_gnu_double.ON_LATTICE_CELL_THRESH
TINY_MOVE = _openmoc_gnu_double.TINY_MOVE
SIMPLE = _openmoc_gnu_double.SIMPLE
LATTICE = _openmoc_gnu_double.LATTICE
class Universe(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Universe, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Universe, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Universe(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Universe
    __del__ = lambda self : None;
    def addCell(self, *args, **kwargs): return _openmoc_gnu_double.Universe_addCell(self, *args, **kwargs)
    def getCells(self): return _openmoc_gnu_double.Universe_getCells(self)
    def getUid(self): return _openmoc_gnu_double.Universe_getUid(self)
    def getId(self): return _openmoc_gnu_double.Universe_getId(self)
    def getType(self): return _openmoc_gnu_double.Universe_getType(self)
    def getNumCells(self): return _openmoc_gnu_double.Universe_getNumCells(self)
    def getFSR(self, *args, **kwargs): return _openmoc_gnu_double.Universe_getFSR(self, *args, **kwargs)
    def getOrigin(self): return _openmoc_gnu_double.Universe_getOrigin(self)
    def setType(self, *args, **kwargs): return _openmoc_gnu_double.Universe_setType(self, *args, **kwargs)
    def setOrigin(self, *args, **kwargs): return _openmoc_gnu_double.Universe_setOrigin(self, *args, **kwargs)
    def findCell(self, *args, **kwargs): return _openmoc_gnu_double.Universe_findCell(self, *args, **kwargs)
    def computeFSRMaps(self): return _openmoc_gnu_double.Universe_computeFSRMaps(self)
    def subdivideCells(self): return _openmoc_gnu_double.Universe_subdivideCells(self)
    def toString(self): return _openmoc_gnu_double.Universe_toString(self)
    def printString(self): return _openmoc_gnu_double.Universe_printString(self)
Universe_swigregister = _openmoc_gnu_double.Universe_swigregister
Universe_swigregister(Universe)

class Lattice(Universe):
    __swig_setmethods__ = {}
    for _s in [Universe]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Lattice, name, value)
    __swig_getmethods__ = {}
    for _s in [Universe]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Lattice, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _openmoc_gnu_double.new_Lattice(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _openmoc_gnu_double.delete_Lattice
    __del__ = lambda self : None;
    def getNumX(self): return _openmoc_gnu_double.Lattice_getNumX(self)
    def getNumY(self): return _openmoc_gnu_double.Lattice_getNumY(self)
    def getOrigin(self): return _openmoc_gnu_double.Lattice_getOrigin(self)
    def getUniverses(self): return _openmoc_gnu_double.Lattice_getUniverses(self)
    def getUniverse(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_getUniverse(self, *args, **kwargs)
    def getWidthX(self): return _openmoc_gnu_double.Lattice_getWidthX(self)
    def getWidthY(self): return _openmoc_gnu_double.Lattice_getWidthY(self)
    def getFSR(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_getFSR(self, *args, **kwargs)
    def setLatticeCells(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_setLatticeCells(self, *args, **kwargs)
    def setUniversePointer(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_setUniversePointer(self, *args, **kwargs)
    def withinBounds(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_withinBounds(self, *args, **kwargs)
    def findCell(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_findCell(self, *args, **kwargs)
    def findNextLatticeCell(self, *args, **kwargs): return _openmoc_gnu_double.Lattice_findNextLatticeCell(self, *args, **kwargs)
    def computeFSRMaps(self): return _openmoc_gnu_double.Lattice_computeFSRMaps(self)
    def toString(self): return _openmoc_gnu_double.Lattice_toString(self)
    def printString(self): return _openmoc_gnu_double.Lattice_printString(self)
Lattice_swigregister = _openmoc_gnu_double.Lattice_swigregister
Lattice_swigregister(Lattice)

# This file is compatible with both classic and new-style classes.


